/**
 * `extractText` feeds the title derived on every flush and the search text. The
 * import chain is run end to end here: an imported document's derived title must
 * equal the title it was created with.
 */
import { describe, it, expect } from "vitest";
import * as Y from "yjs";
import { normalizeImportedMarkdown } from "@stuga/protocol/text/markdown-import";
import { yXmlFragmentToMarkdown, applyMarkdownToYXmlFragment, applyCitedStrEdits } from "@stuga/crdt-ops";
import { extractText, deriveTitle } from "./text-extract.js";

/** A Y.Doc holding `markdown`, seeded the way an import does: a brand-new doc (with
 *  the empty paragraph ensureLoaded seeds) plus one empty-old_string append. */
function importInto(markdown: string): Y.Doc {
  const doc = new Y.Doc();
  const frag = doc.getXmlFragment("default");
  frag.insert(0, [new Y.XmlElement("paragraph")]);
  const current = yXmlFragmentToMarkdown(frag);
  const next = applyCitedStrEdits(current, [{ old_string: "", new_string: markdown }], []);
  applyMarkdownToYXmlFragment(frag, next, { origin: { agent: "importer" }, originalMarkdown: current });
  return doc;
}

describe("extractText", () => {
  it("keeps a heading's formatted runs on ONE line", () => {
    // Each mark boundary is its own text run in the CRDT. Joining runs with newlines
    // split "The `x` Flag" into three lines, so deriveTitle returned just "The" and
    // the index saw three fragments instead of the phrase.
    const doc = importInto("# The `x` Flag\n\nbody text");
    expect(extractText(doc).split("\n")[0]).toBe("The x Flag");
    expect(deriveTitle(extractText(doc))).toBe("The x Flag");
  });

  it("still separates blocks", () => {
    const doc = importInto("# Title\n\nFirst para.\n\nSecond para.");
    const lines = extractText(doc).split("\n").filter((l) => l.trim() !== "");
    expect(lines).toEqual(["Title", "First para.", "Second para."]);
  });

  it("separates list items and table cells", () => {
    const bullets = extractText(importInto("* one\n* two\n* three"));
    expect(bullets.split("\n").filter((l) => l.trim())).toEqual(["one", "two", "three"]);
    // Each cell holds a paragraph, so cells land on their own lines. That's what we
    // want for search (cell values stay distinct tokens rather than running together).
    const table = extractText(importInto("| a | b |\n| --- | --- |\n| 1 | 2 |"));
    expect(table.split("\n").filter((l) => l.trim())).toEqual(["a", "b", "1", "2"]);
  });

  it("separates adjacent footnote definitions, and titles a table-first document by its first cell", () => {
    const notes = extractText(importInto("Claim.[^1] Other.[^2]\n\n[^1]: First source\n[^2]: Second source"));
    expect(notes).toContain("First source\nSecond source");
    expect(deriveTitle(extractText(importInto("| Name | Owner |\n| --- | --- |\n| a | b |")))).toBe("Name");
  });

  it("breaks a line at a hard break", () => {
    // A hardBreak carries no text of its own, so without an explicit newline the
    // lines it divides would run together.
    const doc = importInto("line one\\\nline two");
    expect(extractText(doc).split("\n").filter((l) => l.trim())).toEqual(["line one", "line two"]);
  });

  it("does not leak formatting marks as tags", () => {
    const text = extractText(importInto("# T\n\nsome **bold** and *italic* and `code`"));
    expect(text).toContain("some bold and italic and code");
    expect(text).not.toContain("<");
  });
});

describe("an imported document keeps the title it was created with", () => {
  const cases: Array<[string, string]> = [
    ["# Heading Wins\n\nbody", "ignored.md"],
    ["## Deeper Heading\n\nbody", "ignored.md"],
    ["Setext Heading\n==============\n\nbody", "ignored.md"],
    ["---\ntitle: From Frontmatter\n---\n\nprose with no heading", "ignored.md"],
    ["---\n# Generated by Hugo\ntitle: Hugo Post\ndate: 2026-01-01\n---\n\nbody", "ignored.md"],
    ["plain prose only", "My Notes.md"],
    ["﻿# After A Bom\n\nbody", "ignored.md"],
    ["# The `x` Flag\n\nbody", "ignored.md"],
    ["# **Bold** start\n\nbody", "ignored.md"],
    ["# A *bold* Title\n\nbody", "ignored.md"],
    ["# See [the docs](https://example.com)\n\nbody", "ignored.md"],
    ["# ~~Old~~ New\n\nbody", "ignored.md"],
    ["# Notes [draft]\n\nbody", "ignored.md"],
    ["```yaml\n---\nkind: Pod\n```\n\nApply it.", "pod.md"],
    ["* item one\n---\n\nprose", "list.md"],
    ["> quoted\n---\n\nprose", "quote.md"],
    ["    # indented code\n\nbody", "code.md"],
  ];

  for (const [source, filename] of cases) {
    it(`holds for ${JSON.stringify(source.slice(0, 34))}`, () => {
      const { markdown, title } = normalizeImportedMarkdown(source, { filename });
      // What the import route stores in docs.title vs what the next flush would write.
      expect(deriveTitle(extractText(importInto(markdown)))).toBe(title);
    });
  }
});
